apiVersion: v1
kind: Service
metadata:
  name: whoami-flask-service
spec:
  type: LoadBalancer
  ports:
  - name: whoami-flask
    port: 5000
    targetPort: 5000
  selector:
    app: whoami-flask
