version: '3.3'

services:
  myflask :
    image : myflask:3.0
    ports : 
      - 5000

  nginx :
    depends_on :
      - myflask
    image : nginx
    volumes :
      - .\nginx.conf:/etc/nginx/nginx.conf
    restart : always
    ports : 
      - "80:80"
